name = "MonteCarloCollision"
uuid = "380541f5-4e53-48de-900f-81b1b544904f"
authors = ["Christian Busch"]
version = "1.0.0-DEV"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
